# Generated by Django 4.0.5 on 2022-06-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=20)),
                ('locale', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locations')),
            ],
        ),
    ]
