# Generated by Django 4.0.5 on 2022-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cut_alter_appointments_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='barber',
        ),
    ]
