# Generated by Django 4.0.5 on 2022-06-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_appointments_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.barber'),
        ),
    ]
