# Generated by Django 4.0.5 on 2022-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointments_barber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Appointments'},
        ),
    ]
